const content = [
  "./src/**/*.{js,ts,jsx,tsx,htm,html}",
  "./pages/**/*.{js,ts,jsx,tsx,htm,html}",
];

const plugins = [
  require("@tailwindcss/typography"),
  require("@tailwindcss/forms"),
];

module.exports = {
  content,
  theme: {
    extend: {
      backgroundImage: {
        register: "url('/images/background.png')",
        "listing-card": "url('/images/sample-image.png')",
        "calender-icon": "url('/icons/calender.svg')",
        "cross-icon": "url('/icons/cross.svg')",
        "caret-icon": "url('/icons/caret-right.svg')",
        "caret-double-icon": "url('/icons/caret-double-right.svg')",
        "checkbox-off": "url(/icons/checkbox-off.svg)",
        checkbox: "url(/icons/check_blue_box.svg)",
        "checkbox-off-disabled": "url(/icons/checkbox-off-disabled.svg)",
        "checkbox-disabled": "url(/icons/checkbox-disabled.svg)",
        "radio-off": "url(/icons/radio-off.svg)",
        radio: "url(/icons/radio.svg)",
        "radio-off-disabled": "url(/icons/radio-off-disabled.svg)",
        "radio-disabled": "url(/icons/radio-disabled.svg)",
      },
      backgroundColor: {
        white: {
          DEFAULT: "#ffffff",
          whitest: "#FBF9FE",
          101: "#ddd",
        },
        primary: {
          DEFAULT: "#311E69",
        },
        secondary: {
          DEFAULT: "#2B55E8",
        },
        gray: {
          lightest: "#B4B4B4",
        },
      },
      screens: {
        "max-sm": { max: "639px" },
        "max-md": { max: "767px" },
        "max-900": { max: "900px" },
        "max-lg": { max: "1023px" },
        "max-xl": { max: "1279px" },
        "max-2xl": { max: "1535px" },
      },
      backgroundSize: {},
      backgroundPosition: {},
      borderRadius: {},
      boxShadow: {
        DEFAULT:
          "0 1px 3px 0 rgb(0 0 0 / 10%), 0 1px 2px -1px rgb(0 0 0 / 10%) !important",
        transparent: "transparent",
        card: "2px 13px 54px rgba(105, 95, 151, 0.08);",
        "card-shadow-secondary": "0px 0px 6px rgba(0, 0, 0, 0.1)",
        "input-shadow": "0 8px 15px 0 rgba(38, 53, 66, 0.1)",
        "notification-shadow": "0 10px 20px 0 rgba(38, 53, 66, 0.1)",
        "switch-shadow":
          "0 3px 1px 0 rgba(0, 0, 0, 0.06), 0 3px 8px 0 rgba(0, 0, 0, 0.15)",
        "calendar-shadow": "0 7px 64px 0 rgba(0, 0, 0, 0.07)",
        "app-card": "0 5px 20px 0 rgba(11, 38, 75, 0.1)",
        "btn-shadow-app": "0 10px 20px 0 rgba(38, 53, 66, 0.1)",
        "form-sidebar": "-10px 0 15px 0px rgb(30 30 30 / 62%)",
        header: "0px 4px 24px rgba(0, 0, 0, 0.04)",
        filter: "-2px 0px 12px rgba(0, 0, 0, 0.08)",
        dropdown: "0px 4px 4px rgba(56, 56, 56, 0.04)",
        register: "2px 13px 54px rgba(105, 95, 151, 0.08)",
        cardv2: "0px 0px 6px rgb(0,0,0,0.1)",
        "card-kanban": "2.26px 12.8px 54px rgb(105,95,151,0.14)",
      },
      borderWidth: {},
      border: {
        gray: {
          lightest: "#B4B4B4",
        },
      },
      colors: {
        transparent: "transparent",
        current: "currentColor",
        body: "#FFFFFF",
        primary: {
          DEFAULT: "#311E69",
          light: "#FFF0E3",
          lighter: "#FFFAF5",
          bg: "#FFF4EB",
        },
        secondary: {
          DEFAULT: "#2B55E8",
          light: "#FBF9FE",
          light1: "#747474",
        },
        text: "#000000",
        white: "#FFFFFF",
        inputBg: "#FFF",
        border: {
          DEFAULT: "#D7D7D7",
          gray: {
            light: "#FBF9FE",
          },
          primary: {
            DEFAULT: "#311E69",
          },
          secondary: {
            DEFAULT: "#2B55E8",
          },
          white: {
            DEFAULT: "#ffffff",
          },
        },
        green: {
          DEFAULT: "#47c068",
          110: "#2ECC71",
        },
        gray: {
          DEFAULT: "#2A2A2A",
          light: "#FBF9FE",
          lightest: "#B4B4B4",
          100: "#444444",
          200: "#EAEAEA",
          300: "#F4F4F4",
          400: "#CDCCCC",
        },
        red: {
          DEFAULT: "#d92a27",
          100: "#EC6C6A",
          110: "#C0392B",
        },
        purple: "#7146d4",
        skeleton: "#CDCCCC",
        pink: "#e06588",
        blue: {
          DEFAULT: "#5691e8",
          light: "#47ade8",
        },
        statusLight: {
          100: "#e3f7f8",
          200: "#def8e5",
          300: "#ffe3e2",
          400: "#e3e7ec",
          500: "#fff0e5",
        },
        status: {
          100: "#45c1c5",
          200: "#47c068",
          300: "#d92a27",
          400: "#263542",
          500: "#f08f45",
        },
        disabled: "#f5f6f8",
      },
      container: {},
      gridTemplateColumns: {},
      height: {},
      lineHeight: {},
      placeholder: {
        gray: {
          lightest: "#B4B4B4",
        },
      },
      spacing: {},
      transitionProperty: {
        width: "width",
      },
      width: {},
    },
    fontFamily: {
      body: "Noto Sans",
      heading: '"Josefin Sans", sans-serif',
      sans: '"Nato Sans"',
    },
    container: {
      center: true,
      padding: "1rem",
    },
  },
  safelist: [
    "border-dashed",
    "border-4",
    "p-2",
    "h-40",
    "rounded-lg",
    "max-w-lg",
    "px-[7rem]",
    "max-w-[4rem]",
    "sm:max-w-[8rem]",
    "space-y-5",
    "max-w-[300px]",
    "space-x-4",
    "sm:px-5",
    "translate-x-3",
    "bg-secondary",
    "border-[2px]",
    "border-gray-light",
    "translate-x-[0.5px]",
    "bg-gray-lightest",
    "border",
    "-mt-1",
    "bg-[#3838384D]",
    "pointer-events-none",
    "relative inline-block",
    "h-5",
    "w-5",
    "rounded-full",
    "bg-white",
    "shadow-switch-shadow",
    "transform",
    "ring-0",
    "transition ",
    "ease-in-out",
    "duration-200",
    "opacity-0",
    "duration-100",
    "opacity-100",
    "ease-in",
    "duration-200",
    "absolute ",
    "inset-0",
    "h-full",
    "w-full",
    "flex",
    "items-center",
    "justify-center",
    "transition-opacity",
    "ease-out",
    "border-gray-light",
    "animate-spin",
    "preloader",
  ],
  plugins,
};
